output   = "internal/models"
wipe     = true
no-tests = true

[psql]
  dbname = "CenterDB"
  host   = "localhost"
  port   = 5432
  user   = "postgres"
  pass   = "Hien123456"
  schema = "public"
  sslmode = "disable"