// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// ScheduleSubject is an object representing the database table.
type ScheduleSubject struct {
	ID                int64     `boil:"id" json:"id" toml:"id" yaml:"id"`
	Name              string    `boil:"name" json:"name" toml:"name" yaml:"name"`
	LT                int       `boil:"lt" json:"lt" toml:"lt" yaml:"lt"`
	TH                int       `boil:"th" json:"th" toml:"th" yaml:"th"`
	CreatedAt         time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	CreatedBy         string    `boil:"created_by" json:"created_by" toml:"created_by" yaml:"created_by"`
	ScheduleSubjectID int64     `boil:"schedule__subject_id" json:"schedule__subject_id" toml:"schedule__subject_id" yaml:"schedule__subject_id"`

	R *scheduleSubjectR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L scheduleSubjectL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ScheduleSubjectColumns = struct {
	ID                string
	Name              string
	LT                string
	TH                string
	CreatedAt         string
	CreatedBy         string
	ScheduleSubjectID string
}{
	ID:                "id",
	Name:              "name",
	LT:                "lt",
	TH:                "th",
	CreatedAt:         "created_at",
	CreatedBy:         "created_by",
	ScheduleSubjectID: "schedule__subject_id",
}

// Generated where

var ScheduleSubjectWhere = struct {
	ID                whereHelperint64
	Name              whereHelperstring
	LT                whereHelperint
	TH                whereHelperint
	CreatedAt         whereHelpertime_Time
	CreatedBy         whereHelperstring
	ScheduleSubjectID whereHelperint64
}{
	ID:                whereHelperint64{field: "\"schedule_subject\".\"id\""},
	Name:              whereHelperstring{field: "\"schedule_subject\".\"name\""},
	LT:                whereHelperint{field: "\"schedule_subject\".\"lt\""},
	TH:                whereHelperint{field: "\"schedule_subject\".\"th\""},
	CreatedAt:         whereHelpertime_Time{field: "\"schedule_subject\".\"created_at\""},
	CreatedBy:         whereHelperstring{field: "\"schedule_subject\".\"created_by\""},
	ScheduleSubjectID: whereHelperint64{field: "\"schedule_subject\".\"schedule__subject_id\""},
}

// ScheduleSubjectRels is where relationship names are stored.
var ScheduleSubjectRels = struct {
	ScheduleSubject string
}{
	ScheduleSubject: "ScheduleSubject",
}

// scheduleSubjectR is where relationships are stored.
type scheduleSubjectR struct {
	ScheduleSubject *ScheduleContent
}

// NewStruct creates a new relationship struct
func (*scheduleSubjectR) NewStruct() *scheduleSubjectR {
	return &scheduleSubjectR{}
}

// scheduleSubjectL is where Load methods for each relationship are stored.
type scheduleSubjectL struct{}

var (
	scheduleSubjectAllColumns            = []string{"id", "name", "lt", "th", "created_at", "created_by", "schedule__subject_id"}
	scheduleSubjectColumnsWithoutDefault = []string{"name", "lt", "th", "created_by", "schedule__subject_id"}
	scheduleSubjectColumnsWithDefault    = []string{"id", "created_at"}
	scheduleSubjectPrimaryKeyColumns     = []string{"id"}
)

type (
	// ScheduleSubjectSlice is an alias for a slice of pointers to ScheduleSubject.
	// This should generally be used opposed to []ScheduleSubject.
	ScheduleSubjectSlice []*ScheduleSubject
	// ScheduleSubjectHook is the signature for custom ScheduleSubject hook methods
	ScheduleSubjectHook func(context.Context, boil.ContextExecutor, *ScheduleSubject) error

	scheduleSubjectQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	scheduleSubjectType                 = reflect.TypeOf(&ScheduleSubject{})
	scheduleSubjectMapping              = queries.MakeStructMapping(scheduleSubjectType)
	scheduleSubjectPrimaryKeyMapping, _ = queries.BindMapping(scheduleSubjectType, scheduleSubjectMapping, scheduleSubjectPrimaryKeyColumns)
	scheduleSubjectInsertCacheMut       sync.RWMutex
	scheduleSubjectInsertCache          = make(map[string]insertCache)
	scheduleSubjectUpdateCacheMut       sync.RWMutex
	scheduleSubjectUpdateCache          = make(map[string]updateCache)
	scheduleSubjectUpsertCacheMut       sync.RWMutex
	scheduleSubjectUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var scheduleSubjectBeforeInsertHooks []ScheduleSubjectHook
var scheduleSubjectBeforeUpdateHooks []ScheduleSubjectHook
var scheduleSubjectBeforeDeleteHooks []ScheduleSubjectHook
var scheduleSubjectBeforeUpsertHooks []ScheduleSubjectHook

var scheduleSubjectAfterInsertHooks []ScheduleSubjectHook
var scheduleSubjectAfterSelectHooks []ScheduleSubjectHook
var scheduleSubjectAfterUpdateHooks []ScheduleSubjectHook
var scheduleSubjectAfterDeleteHooks []ScheduleSubjectHook
var scheduleSubjectAfterUpsertHooks []ScheduleSubjectHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *ScheduleSubject) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scheduleSubjectBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *ScheduleSubject) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scheduleSubjectBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *ScheduleSubject) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scheduleSubjectBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *ScheduleSubject) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scheduleSubjectBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *ScheduleSubject) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scheduleSubjectAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *ScheduleSubject) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scheduleSubjectAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *ScheduleSubject) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scheduleSubjectAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *ScheduleSubject) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scheduleSubjectAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *ScheduleSubject) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scheduleSubjectAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddScheduleSubjectHook registers your hook function for all future operations.
func AddScheduleSubjectHook(hookPoint boil.HookPoint, scheduleSubjectHook ScheduleSubjectHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		scheduleSubjectBeforeInsertHooks = append(scheduleSubjectBeforeInsertHooks, scheduleSubjectHook)
	case boil.BeforeUpdateHook:
		scheduleSubjectBeforeUpdateHooks = append(scheduleSubjectBeforeUpdateHooks, scheduleSubjectHook)
	case boil.BeforeDeleteHook:
		scheduleSubjectBeforeDeleteHooks = append(scheduleSubjectBeforeDeleteHooks, scheduleSubjectHook)
	case boil.BeforeUpsertHook:
		scheduleSubjectBeforeUpsertHooks = append(scheduleSubjectBeforeUpsertHooks, scheduleSubjectHook)
	case boil.AfterInsertHook:
		scheduleSubjectAfterInsertHooks = append(scheduleSubjectAfterInsertHooks, scheduleSubjectHook)
	case boil.AfterSelectHook:
		scheduleSubjectAfterSelectHooks = append(scheduleSubjectAfterSelectHooks, scheduleSubjectHook)
	case boil.AfterUpdateHook:
		scheduleSubjectAfterUpdateHooks = append(scheduleSubjectAfterUpdateHooks, scheduleSubjectHook)
	case boil.AfterDeleteHook:
		scheduleSubjectAfterDeleteHooks = append(scheduleSubjectAfterDeleteHooks, scheduleSubjectHook)
	case boil.AfterUpsertHook:
		scheduleSubjectAfterUpsertHooks = append(scheduleSubjectAfterUpsertHooks, scheduleSubjectHook)
	}
}

// One returns a single scheduleSubject record from the query.
func (q scheduleSubjectQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ScheduleSubject, error) {
	o := &ScheduleSubject{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for schedule_subject")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all ScheduleSubject records from the query.
func (q scheduleSubjectQuery) All(ctx context.Context, exec boil.ContextExecutor) (ScheduleSubjectSlice, error) {
	var o []*ScheduleSubject

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to ScheduleSubject slice")
	}

	if len(scheduleSubjectAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all ScheduleSubject records in the query.
func (q scheduleSubjectQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count schedule_subject rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q scheduleSubjectQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if schedule_subject exists")
	}

	return count > 0, nil
}

// ScheduleSubject pointed to by the foreign key.
func (o *ScheduleSubject) ScheduleSubject(mods ...qm.QueryMod) scheduleContentQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ScheduleSubjectID),
	}

	queryMods = append(queryMods, mods...)

	query := ScheduleContents(queryMods...)
	queries.SetFrom(query.Query, "\"schedule_content\"")

	return query
}

// LoadScheduleSubject allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (scheduleSubjectL) LoadScheduleSubject(ctx context.Context, e boil.ContextExecutor, singular bool, maybeScheduleSubject interface{}, mods queries.Applicator) error {
	var slice []*ScheduleSubject
	var object *ScheduleSubject

	if singular {
		object = maybeScheduleSubject.(*ScheduleSubject)
	} else {
		slice = *maybeScheduleSubject.(*[]*ScheduleSubject)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &scheduleSubjectR{}
		}
		args = append(args, object.ScheduleSubjectID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &scheduleSubjectR{}
			}

			for _, a := range args {
				if a == obj.ScheduleSubjectID {
					continue Outer
				}
			}

			args = append(args, obj.ScheduleSubjectID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(qm.From(`schedule_content`), qm.WhereIn(`schedule_content.id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load ScheduleContent")
	}

	var resultSlice []*ScheduleContent
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice ScheduleContent")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for schedule_content")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for schedule_content")
	}

	if len(scheduleSubjectAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.ScheduleSubject = foreign
		if foreign.R == nil {
			foreign.R = &scheduleContentR{}
		}
		foreign.R.ScheduleSubjectScheduleSubjects = append(foreign.R.ScheduleSubjectScheduleSubjects, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ScheduleSubjectID == foreign.ID {
				local.R.ScheduleSubject = foreign
				if foreign.R == nil {
					foreign.R = &scheduleContentR{}
				}
				foreign.R.ScheduleSubjectScheduleSubjects = append(foreign.R.ScheduleSubjectScheduleSubjects, local)
				break
			}
		}
	}

	return nil
}

// SetScheduleSubject of the scheduleSubject to the related item.
// Sets o.R.ScheduleSubject to related.
// Adds o to related.R.ScheduleSubjectScheduleSubjects.
func (o *ScheduleSubject) SetScheduleSubject(ctx context.Context, exec boil.ContextExecutor, insert bool, related *ScheduleContent) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"schedule_subject\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"schedule__subject_id"}),
		strmangle.WhereClause("\"", "\"", 2, scheduleSubjectPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ScheduleSubjectID = related.ID
	if o.R == nil {
		o.R = &scheduleSubjectR{
			ScheduleSubject: related,
		}
	} else {
		o.R.ScheduleSubject = related
	}

	if related.R == nil {
		related.R = &scheduleContentR{
			ScheduleSubjectScheduleSubjects: ScheduleSubjectSlice{o},
		}
	} else {
		related.R.ScheduleSubjectScheduleSubjects = append(related.R.ScheduleSubjectScheduleSubjects, o)
	}

	return nil
}

// ScheduleSubjects retrieves all the records using an executor.
func ScheduleSubjects(mods ...qm.QueryMod) scheduleSubjectQuery {
	mods = append(mods, qm.From("\"schedule_subject\""))
	return scheduleSubjectQuery{NewQuery(mods...)}
}

// FindScheduleSubject retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindScheduleSubject(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*ScheduleSubject, error) {
	scheduleSubjectObj := &ScheduleSubject{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"schedule_subject\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, scheduleSubjectObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from schedule_subject")
	}

	return scheduleSubjectObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ScheduleSubject) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no schedule_subject provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(scheduleSubjectColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	scheduleSubjectInsertCacheMut.RLock()
	cache, cached := scheduleSubjectInsertCache[key]
	scheduleSubjectInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			scheduleSubjectAllColumns,
			scheduleSubjectColumnsWithDefault,
			scheduleSubjectColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(scheduleSubjectType, scheduleSubjectMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(scheduleSubjectType, scheduleSubjectMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"schedule_subject\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"schedule_subject\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into schedule_subject")
	}

	if !cached {
		scheduleSubjectInsertCacheMut.Lock()
		scheduleSubjectInsertCache[key] = cache
		scheduleSubjectInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the ScheduleSubject.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ScheduleSubject) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	scheduleSubjectUpdateCacheMut.RLock()
	cache, cached := scheduleSubjectUpdateCache[key]
	scheduleSubjectUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			scheduleSubjectAllColumns,
			scheduleSubjectPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update schedule_subject, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"schedule_subject\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, scheduleSubjectPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(scheduleSubjectType, scheduleSubjectMapping, append(wl, scheduleSubjectPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update schedule_subject row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for schedule_subject")
	}

	if !cached {
		scheduleSubjectUpdateCacheMut.Lock()
		scheduleSubjectUpdateCache[key] = cache
		scheduleSubjectUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q scheduleSubjectQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for schedule_subject")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for schedule_subject")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ScheduleSubjectSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), scheduleSubjectPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"schedule_subject\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, scheduleSubjectPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in scheduleSubject slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all scheduleSubject")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ScheduleSubject) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no schedule_subject provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(scheduleSubjectColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	scheduleSubjectUpsertCacheMut.RLock()
	cache, cached := scheduleSubjectUpsertCache[key]
	scheduleSubjectUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			scheduleSubjectAllColumns,
			scheduleSubjectColumnsWithDefault,
			scheduleSubjectColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			scheduleSubjectAllColumns,
			scheduleSubjectPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert schedule_subject, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(scheduleSubjectPrimaryKeyColumns))
			copy(conflict, scheduleSubjectPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"schedule_subject\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(scheduleSubjectType, scheduleSubjectMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(scheduleSubjectType, scheduleSubjectMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert schedule_subject")
	}

	if !cached {
		scheduleSubjectUpsertCacheMut.Lock()
		scheduleSubjectUpsertCache[key] = cache
		scheduleSubjectUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single ScheduleSubject record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ScheduleSubject) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no ScheduleSubject provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), scheduleSubjectPrimaryKeyMapping)
	sql := "DELETE FROM \"schedule_subject\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from schedule_subject")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for schedule_subject")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q scheduleSubjectQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no scheduleSubjectQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from schedule_subject")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for schedule_subject")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ScheduleSubjectSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(scheduleSubjectBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), scheduleSubjectPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"schedule_subject\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, scheduleSubjectPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from scheduleSubject slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for schedule_subject")
	}

	if len(scheduleSubjectAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ScheduleSubject) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindScheduleSubject(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ScheduleSubjectSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ScheduleSubjectSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), scheduleSubjectPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"schedule_subject\".* FROM \"schedule_subject\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, scheduleSubjectPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in ScheduleSubjectSlice")
	}

	*o = slice

	return nil
}

// ScheduleSubjectExists checks if the ScheduleSubject row exists.
func ScheduleSubjectExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"schedule_subject\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if schedule_subject exists")
	}

	return exists, nil
}
